server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进 Eureka 服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Clarityed/springcloud-config.git # GitHub上面的 git 仓库名字
          #### 搜索目录
          search-paths:
            - springcloud-config
          basedir: F:\study\code\java\idea_code\springcloud-config
      #### 读取分支
      label: main

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka