spring:
  profiles:
    active: test
  # active: dev # 表示开发环境
    # ${spring.application.name}-${spring.profile.active}.${spring.cloud.nacos.config.file-extension}
    # nacos-config-client-test.yaml
    # active: test # 表示测试环境
